### ISSUE TITLE
调研Mac环境下是否可以正常运行

### ISSUE THREAD

**Issue by JusterZhu** [WELL-E/AutoUpdater#19]
将搭载GeneralUpdate组件的应用程序在Mac环境下运行测试

**Comment by JaneConan** [comment]
目前因为GeneralUpdate.Single项目中，有引用

    using System.Windows;
    using System.Windows.Threading;

所以在Mac无法还原这个基础项目，建议做成根据操作系统环境判定是否启用这部分受影响的工具类

受影响的项目如下
<img width="422" alt="image" src="https://user-images.githubusercontent.com/26090153/154793908-d249e667-88cb-47f8-b4a9-a47f2d971e16.png">

运行环境为
<img width="586" alt="image" src="https://user-images.githubusercontent.com/26090153/154793922-e37db290-887a-4176-9554-7c1c23116699.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/26090153/154793937-b98138be-7402-4ae9-8118-a284c863a347.png">


VS for Mac 2019 以及最新的Preview版本，均输出：

获取项目 /Users/mac/GitHub/JaneConan/AutoUpdater/src/GeneralUpdate.AspNetCore/GeneralUpdate.AspNetCore.csproj 的还原信息
获取项目 /Users/mac/GitHub/JaneConan/AutoUpdater/src/AutoUpdate.WpfNet6-Sample/AutoUpdate.WpfNet6-Sample.csproj 的还原信息
/usr/local/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5) : error NETSDK1100: 需使用 Windows 才能构建 Windows 桌面应用程序。
无法为项目创建包规范。/Users/mac/GitHub/JaneConan/AutoUpdater/src/AutoUpdate.WpfNet6-Sample/AutoUpdate.WpfNet6-Sample.csproj

目前情况建议部分standard类库向.net6迁移

**Comment by JusterZhu** [comment]
> 目前因为GeneralUpdate.Single项目中，有引用
> 
> ```
> using System.Windows;
> using System.Windows.Threading;
> ```
> 
> 所以在Mac无法还原这个基础项目，建议做成根据操作系统环境判定是否启用这部分受影响的工具类
> 
> 受影响的项目如下 <img alt="image" width="422" src="https://user-images.githubusercontent.com/26090153/154793908-d249e667-88cb-47f8-b4a9-a47f2d971e16.png">
> 
> 运行环境为 <img alt="image" width="586" src="https://user-images.githubusercontent.com/26090153/154793922-e37db290-887a-4176-9554-7c1c23116699.png"> <img alt="image" width="562" src="https://user-images.githubusercontent.com/26090153/154793937-b98138be-7402-4ae9-8118-a284c863a347.png">
> 
> VS for Mac 2019 以及最新的Preview版本，均输出：
> 
> 获取项目 /Users/mac/GitHub/JaneConan/AutoUpdater/src/GeneralUpdate.AspNetCore/GeneralUpdate.AspNetCore.csproj 的还原信息 获取项目 /Users/mac/GitHub/JaneConan/AutoUpdater/src/AutoUpdate.WpfNet6-Sample/AutoUpdate.WpfNet6-Sample.csproj 的还原信息 /usr/local/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5) : error NETSDK1100: 需使用 Windows 才能构建 Windows 桌面应用程序。 无法为项目创建包规范。/Users/mac/GitHub/JaneConan/AutoUpdater/src/AutoUpdate.WpfNet6-Sample/AutoUpdate.WpfNet6-Sample.csproj
> 
> 目前情况建议部分standard类库向.net6迁移

这一块的测试是这样的，把MAUI的程序可执行文件放在mac上看看能不能运行。因为MAC的VS对MAUI支持并不太好，所以这样测试不太能看出效果。

**Comment by JaneConan** [comment]
好滴，那我把MAUI发布一下，在Mac试着运行~ 我这边也有Linux机器，包括arm64的Linux，另外一个issue我也可以试试~
