### ISSUE TITLE
AutoUpdater下载后调试问题

### ISSUE THREAD

**Issue by 858594355** [WELL-E/AutoUpdater#2]
您好，我下载您的这个代码后，在使用时遇到一些问题，需要您的帮助。
一：代码下载后，启动调试时，参数直接就是默认的。想知道使用时传入参数的方法。
二：关于UpdaterEx工程的说明。这个工程的作用是什么？

**Comment by zhuzhen723723** [comment]
首先说明清楚一些概念：
1.autoupdate是一个独立的程序
2.客户端程序想要进行更新，就需要把autoupdate这个程序启动，在启动的时候给它传参数。autoupdate的参数来源就是这个时候传递的。启动程序传参，参考MSDN:https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.process?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(System.Diagnostics.Process);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2

**Comment by zhuzhen723723** [comment]
首先说明清楚一些概念：
1.autoupdate是一个独立的程序
2.客户端程序想要进行更新，就需要把autoupdate这个程序启动，在启动的时候给它传参数。autoupdate的参数来源就是这个时候传递的。启动程序传参，参考MSDN:https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.process?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(System.Diagnostics.Process);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2

**Comment by zhuzhen723723** [comment]
只要不是框架级别的更新都是可以更新的。 不管你迭代多少次跨了多少个版本，你把最终的包放到服务器上就行了。这个里面没有涉及到增量更新，所以你更新多了直接把所有的新文件覆盖上去就行了。
