### ISSUE TITLE
WpfNet6-Sample增加下载过程信息文字提示可视化（WpfNet6-Sample Added text prompt visualization of download process information）

### ISSUE THREAD

**Issue by JaneConan** [WELL-E/AutoUpdater#23]
为了提示用户下载的进程描述，除了进度条，在必要的时候（企鹅群也在问找不到服务器地址，可能因为他们找不到那个server项目）进行提示，故在窗体中Tip5的区域，增加了对Message信息的输出。

相关代码在Fork的repo中提交了

[https://github.com/JaneConan/AutoUpdater](https://github.com/JaneConan/AutoUpdater)

准备向主库申请pr，和您进行代码审查进行尝试，以便于将来整合MAUI时参考。

![image](https://user-images.githubusercontent.com/26090153/154792411-317f0f6a-1abb-4014-a06e-8c55c517abe0.png)

![image](https://user-images.githubusercontent.com/26090153/154792863-47b2dad2-3ba9-47b7-b562-e4310f4bbb6c.png)

![image](https://user-images.githubusercontent.com/26090153/154792848-5a150807-610d-47b3-b014-82ce33687d17.png)

**Comment by JaneConan** [comment]
而且目前即使开了咱们的MinimalService项目，也会抛出一些异常，所以根据还是有必要加上一些文字类信息的

![image](https://user-images.githubusercontent.com/26090153/154793172-6ad2c02d-55db-4f97-bc12-1e011387d934.png)

![image](https://user-images.githubusercontent.com/26090153/154793191-e54ec4f2-ffb5-4662-8c47-eed97d9a12fa.png)

**Comment by JusterZhu** [comment]
> 而且目前即使开了咱们的MinimalService项目，也会抛出一些异常，所以根据还是有必要加上一些文字类信息的
> 
> ![image](https://user-images.githubusercontent.com/26090153/154793172-6ad2c02d-55db-4f97-bc12-1e011387d934.png)
> 
> ![image](https://user-images.githubusercontent.com/26090153/154793191-e54ec4f2-ffb5-4662-8c47-eed97d9a12fa.png)

这块已经修复了，记得每天同步最新代码。我每天都在提交PR.

**Comment by JusterZhu** [comment]
> 为了提示用户下载的进程描述，除了进度条，在必要的时候（企鹅群也在问找不到服务器地址，可能因为他们找不到那个server项目）进行提示，故在窗体中Tip5的区域，增加了对Message信息的输出。
> 
> 相关代码在Fork的repo中提交了
> 
> https://github.com/JaneConan/AutoUpdater
> 
> 准备向主库申请pr，和您进行代码审查进行尝试，以便于将来整合MAUI时参考。
> 
> ![image](https://user-images.githubusercontent.com/26090153/154792411-317f0f6a-1abb-4014-a06e-8c55c517abe0.png)
> 
> ![image](https://user-images.githubusercontent.com/26090153/154792863-47b2dad2-3ba9-47b7-b562-e4310f4bbb6c.png)
> 
> ![image](https://user-images.githubusercontent.com/26090153/154792848-5a150807-610d-47b3-b014-82ce33687d17.png)

这一块的修改，直接提交PR我来审核吧。我这里看不到你所有的修改。

**Comment by JaneConan** [comment]
好滴 已申请PR
