### ISSUE TITLE
MinimalService项目是否考虑可在外部配置

### ISSUE THREAD

**Issue by JaneConan** [WELL-E/AutoUpdater#24]
1、和GeneralUpdate.Core和GeneralUpdate.ClientCore组件开发搭配，结合sqlite或json静态文件在程序外部进行配置，而非写死代码
2、增加类似swagger之类的可视化接口工具，便于更多的第一次上手的朋友们，更容易上手并了解项目
3、结合项目结构，梳理example的启动顺序和相互依赖

**Comment by JusterZhu** [comment]
> 1、和GeneralUpdate.Core和GeneralUpdate.ClientCore组件开发搭配，结合sqlite或json静态文件在程序外部进行配置，而非写死代码 2、增加类似swagger之类的可视化接口工具，便于更多的第一次上手的朋友们，更容易上手并了解项目 3、结合项目结构，梳理example的启动顺序和相互依赖

2和3都可以，1如果能达到安装nuget之后自动在当前lib里自动添加json这种效果还好点。但是变相会增加更新内容这个有考虑周全点的方案能试试。
