### ISSUE TITLE
Nuget包还不是最新版本

### ISSUE THREAD

**Issue by uoyoCsharp** [WELL-E/AutoUpdater#38]
我在nuget上面搜索看到好几个包都还是去年9月份的版本。没有新的Model类。
请问下什么时候准备发布新nuget包呢？

还有就是在示例代码种我看到这个model同一个属性好像在表示两个不同的概念，是不是不太合适？
![image](https://user-images.githubusercontent.com/32832304/159620022-c1647a98-2954-4237-9c51-309435b61fa1.png)

**Comment by JusterZhu** [comment]
最新的版本还处于preview阶段，需要测试修改解决掉大部分bug才能发到nuget平台上。clientversion这块在还在弄规则，正式发布我会在微信公众号上通知的。

**Comment by JusterZhu** [comment]
nuget平台上已更新。
