### ISSUE TITLE
wpf应用怎么部署自动升级 

### ISSUE THREAD

**Issue by ololo2013** [WELL-E/AutoUpdater#39]
1，客户端主程序版本号在什么地方设置？ AssemblyInfo.cs?
2，客户端：代码怎么写？
3，更新升级包：除了update.zip,是不是还有一个update.xml,存放新版本号及更新说明
4，更新组件：升级程序需要设置哪些：下载路径、客户端主程序名；是在升级组件配置里设置；或是在客户端主程序的配置设置？
5，是不是把升级程序，存放在客户端主程序同一目录？

**Comment by JusterZhu** [comment]
1，3，4的配置都集中在ClientParameter对象中，ref：https://github.com/WELL-E/AutoUpdater/blob/master/src/GeneralUpdate.Core/Models/ClientParameter.cs

2，所有的示例代码在源代码中需自行下载AutoUpdate开头的工程都是的，客户端代码编写参考，ref：https://github.com/WELL-E/AutoUpdater/tree/master/src/AutoUpdate.ClientCore

5，是的
