### ISSUE TITLE
AutoUpdate.WpfApp项目启动出错

### ISSUE THREAD

**Issue by zhaoyang2296316065** [WELL-E/AutoUpdater#4]
**AutoUpdate.WpfApp项目启动出错**

错误描述：System.InvalidOperationException:“不能在同一 AppDomain 中创建多个 System.Windows.Application 实例。”

错误位置：App.xaml.cs 第48行 ` var application = new App();`

**Comment by JusterZhu** [comment]
已修复，添加Program启动文件运行实例代码即可。
