### ISSUE TITLE
萌新问题

### ISSUE THREAD

**Issue by qq1176914912** [WELL-E/AutoUpdater#45]
1、关于更新程序是否需要和主程序放在同一个目录下，是将主程序和更新程序的debug目录下的所有文件移动到同一文件夹下吗？
2、GeneralUpdate.PacketTool打包程序，我理解的第一个地址是需要打包的数据，第二行和第三行有啥区别？对打包数据有要求吗？
3、我可不可以直接用压缩工具做一个压缩包当做更新包？
4、现在的要对客户端更新是不是必须要有单独的更新程序、主程序、服务端三者，不能只有服务端和主程序，主程序中融合更新程序

**Comment by JusterZhu** [comment]
1.是的
2.例如：你有两个版本v1.0.0.0 和 v1.1.1.1 ，第一个地址就写v1.0.0.0的文件夹路径 第二文本框里写 v1.1.1.1的文件夹路径 第三个文本框写你更新包最终要打包到哪个路径下。
3.可以，它的作用就是这个。
4.是的，三者才能组成一个更新体系。

**Comment by qq1176914912** [comment]
5、流程图中说第一步主程序先去下载更新程序的更新包，我看项目中更新程序更新下载主程序时用的连接貌似和第一步是一样的，说明他们下载的东西是一样的，那会不会重复下载呢？
6、如果想要更新程序所用的下载地址和更新客户端的下载地址不同，是不是要在server中增加app.MapGet（）和对应的方法？

**Comment by qq1176914912** [comment]
我下载了您的这个源码 更改了AutoUpdate.MinimalService里面的下载路径为我的
![image](https://user-images.githubusercontent.com/79817742/162245539-4e8a012a-bdc4-4698-8f9d-446c9d7f01ae.png)
![image](https://user-images.githubusercontent.com/79817742/162245799-82205849-51f3-4934-a324-0c5a3ef57cd9.png)
也更改了主程序中的本地程序地址
![image](https://user-images.githubusercontent.com/79817742/162246039-1709db24-e9b4-4b04-8131-d45971ab53a2.png)
也把更新程序AutoUpdate.Core中App.xaml.cs的死值改为了活值
![image](https://user-images.githubusercontent.com/79817742/162246302-499189b0-01b3-427b-a699-374e8140070a.png)
将主程序和更新程序放到同一目录
![image](https://user-images.githubusercontent.com/79817742/162246447-0079e012-2497-404c-a168-ad09abe166a5.png)
启动主程序后点击按钮没有任何反应
![image](https://user-images.githubusercontent.com/79817742/162246562-48f70292-0e48-441f-9aac-8adc0462e771.png)
是我漏掉哪里了吗？

**Comment by qq1176914912** [comment]
![image](https://user-images.githubusercontent.com/79817742/162349482-184ad8fa-b480-4648-8525-43087e91d5a8.png)
这种不使用数据库的怎么结合clientType来区分更新程序的更新包和主程序的更新包

**Comment by qq1176914912** [comment]
问题![image](https://user-images.githubusercontent.com/79817742/162356632-8d08fb76-ad82-4a63-8995-22ade1866341.png)

**Comment by JusterZhu** [comment]
> ![image](https://user-images.githubusercontent.com/79817742/162349482-184ad8fa-b480-4648-8525-43087e91d5a8.png) 这种不使用数据库的怎么结合clientType来区分更新程序的更新包和主程序的更新包

我在TODO的那行注释里写了说明

**Comment by JusterZhu** [comment]
> ![image](https://user-images.githubusercontent.com/79817742/162356632-8d08fb76-ad82-4a63-8995-22ade1866341.png) 我现在将更新程序和主程序的版本都设置的比服务器包的版本高 前者是1.1.1.5 后者是1.1.1.2 ![image](https://user-images.githubusercontent.com/79817742/162356717-a67da2f8-72fa-4907-9610-84c666d03615.png) 为什么也下载下了呢，是没有版本比较的功能吗？

比较功能有的，你需要在server端调试一下。整个链路都是跑通过的不会出现这种问题

**Comment by qq1176914912** [comment]
> > ![image](https://user-images.githubusercontent.com/79817742/162356632-8d08fb76-ad82-4a63-8995-22ade1866341.png) 我现在将更新程序和主程序的版本都设置的比服务器包的版本高 前者是1.1.1.5 后者是1.1.1.2 ![image](https://user-images.githubusercontent.com/79817742/162356717-a67da2f8-72fa-4907-9610-84c666d03615.png) 为什么也下载下了呢，是没有版本比较的功能吗？
> 
> 比较功能有的，你需要在server端调试一下。整个链路都是跑通过的不会出现这种问题

哦哦这个需要自己写，我以为是内部就做了

**Comment by qq1176914912** [comment]
![image](https://user-images.githubusercontent.com/79817742/162375367-ca0ee53c-9a6c-4a51-aa0b-dedc804d5cfc.png)
我现在将服务器上的文件更改为了两个 主程序启动后下载完了两个 没有关闭主程序打开更新程序，请问代码是从哪里去打开的更新程序，我想寻找一下原因

**Comment by qq1176914912** [comment]
我现在尝试调试源码的主程序 又出现了这个错误
![image](https://user-images.githubusercontent.com/79817742/162400339-e79f97b6-652c-410f-b559-e40c0c101843.png)
占用问题 我重启了电脑还是这样

**Comment by JusterZhu** [comment]
> ![image](https://user-images.githubusercontent.com/79817742/162375367-ca0ee53c-9a6c-4a51-aa0b-dedc804d5cfc.png) 我现在将服务器上的文件更改为了两个 主程序启动后下载完了两个 没有关闭主程序打开更新程序,我看了文件夹也只是吧第一个下载的压缩包解压了，第二个没有解压，但是只留一个文件（留那个都行），又能正常打开更新程序更新，就改成两个文件后不能打开更新程序，好迷茫，您代码是从哪里去启动的更新程序，我想看看毛病出在哪里

这个需要检查路径怎么配置的

**Comment by qq1176914912** [comment]
> > ![image](https://user-images.githubusercontent.com/79817742/162375367-ca0ee53c-9a6c-4a51-aa0b-dedc804d5cfc.png) 我现在将服务器上的文件更改为了两个 主程序启动后下载完了两个 没有关闭主程序打开更新程序,我看了文件夹也只是吧第一个下载的压缩包解压了，第二个没有解压，但是只留一个文件（留那个都行），又能正常打开更新程序更新，就改成两个文件后不能打开更新程序，好迷茫，您代码是从哪里去启动的更新程序，我想看看毛病出在哪里
> 
> 这个需要检查路径怎么配置的
因为遇到了占用问题，我就把占用的这句代码注释掉了
![image](https://user-images.githubusercontent.com/79817742/162404677-7023a2f6-214b-413f-999e-a112d7bbc588.png)
然后我调试找了一下 在下图中 当第二个压缩包到达时 解压过程中会报一个目标文件夹不存在的错误
![image](https://user-images.githubusercontent.com/79817742/162404552-60a11acc-11f4-4bfd-b7fe-8a3e4bbc0110.png)

**Comment by qq1176914912** [comment]
> > > > ![image](https://user-images.githubusercontent.com/79817742/162375367-ca0ee53c-9a6c-4a51-aa0b-dedc804d5cfc.png) 我现在将服务器上的文件更改为了两个 主程序启动后下载完了两个 没有关闭主程序打开更新程序,我看了文件夹也只是吧第一个下载的压缩包解压了，第二个没有解压，但是只留一个文件（留那个都行），又能正常打开更新程序更新，就改成两个文件后不能打开更新程序，好迷茫，您代码是从哪里去启动的更新程序，我想看看毛病出在哪里
> > > 
> > > 
> > > 这个需要检查路径怎么配置的
> > > 因为遇到了占用问题，我就把占用的这句代码注释掉了
> > > ![image](https://user-images.githubusercontent.com/79817742/162404677-7023a2f6-214b-413f-999e-a112d7bbc588.png)
> > > 然后我调试找了一下 在下图中 当第二个压缩包到达时 解压过程中会报一个目标文件夹不存在的错误
> > > ![image](https://user-images.githubusercontent.com/79817742/162404552-60a11acc-11f4-4bfd-b7fe-8a3e4bbc0110.png)
> 
> 我不是很清楚你现在的状况，按照我的经验给你提几个建议你看看： 1.检查一下项目的引用是否正常，如果引用多了的话其它的DLL正在使用就会出现占用的情况 2.进程是否正常关闭线程是否正常推出 3.更新包（.zip）里的文件内容是否重复，版本号信息必须不一样。MD5码要对上

关于第三点，多个更新包版本不一样，但是内容一样，也可能出现错误？
还有关于服务器配置下载路径的这里
![image](https://user-images.githubusercontent.com/79817742/162410669-a27150e7-8f90-4e0c-9493-9b2a15ab3628.png)
第二个是时间这个时间是随便填吗，第五个的name是干什么用的 也可以随便填吗？

**Comment by JusterZhu** [comment]
1.更新的意义就是把不同文件的更新统一，都一样了还更新啥呀。
2.时间戳有先后时序的
3.那个name是更新包的名称也要不一样

**Comment by qq1176914912** [comment]
> 1.更新的意义就是把不同文件的更新统一，都一样了还更新啥呀。 2.时间戳有先后时序的 3.那个name是更新包的名称也要不一样

2、先后时序会影响后面解压更新时版本的顺序吗，例如1.1.1.1的版本的更新包，我写时间是2021年xxx，而1.1.1.2版本的更新包的时间我写2020年xxx,也就是新版本的时间比旧版本的时间还早，这么写会不会有影响，还是说1.1.1.2的更新包的时间必须要比1.1.1.1的更新包的时间晚，如果这样 我是不是可以把他理解为更新包的创建时间

**Comment by qq1176914912** [comment]
> 1.更新的意义就是把不同文件的更新统一，都一样了还更新啥呀。 2.时间戳有先后时序的 3.那个name是更新包的名称也要不一样

3、这个名字如果我增加了类型的判断，不是同时执行的下载，就是先更新助手然后再更新主程序时，更新助手的更新包的这个名字可以和主程序更新包的这个名字一样吗，还是说不管怎样都不能一样

**Comment by qq1176914912** [comment]
> > 1.更新的意义就是把不同文件的更新统一，都一样了还更新啥呀。 2.时间戳有先后时序的 3.那个name是更新包的名称也要不一样
> 
> 3、这个名字不同主程序的更新包和主程序的更新包之间、更新助手的更新包和更新助手的更新包之间肯定是不能相同，那主程序的更新包和更新助手的更新包可以相同吗

**Comment by JusterZhu** [comment]
> > > 1.更新的意义就是把不同文件的更新统一，都一样了还更新啥呀。 2.时间戳有先后时序的 3.那个name是更新包的名称也要不一样
> > 
> > 
> > 3、这个名字不同主程序的更新包和主程序的更新包之间、更新助手的更新包和更新助手的更新包之间肯定是不能相同，那主程序的更新包和更新助手的更新包可以相同吗

建议不同，不然时间长了你自己都分不清楚、也能方便你自己排查问题到底是哪个包更新出错了。

**Comment by qq1176914912** [comment]
2、先后时序会影响后面解压更新时版本的顺序吗，例如1.1.1.1的版本的更新包，我写时间是2021年xxx，而1.1.1.2版本的更新包的时间我写2020年xxx,也就是新版本的时间比旧版本的时间还早，这么写会不会有影响，还是说1.1.1.2的更新包的时间必须要比1.1.1.1的更新包的时间晚，如果这样 我是不是可以把他理解为更新包的创建时间

**Comment by qq1176914912** [comment]
> > > > ![image](https://user-images.githubusercontent.com/79817742/162375367-ca0ee53c-9a6c-4a51-aa0b-dedc804d5cfc.png) 我现在将服务器上的文件更改为了两个 主程序启动后下载完了两个 没有关闭主程序打开更新程序,我看了文件夹也只是吧第一个下载的压缩包解压了，第二个没有解压，但是只留一个文件（留那个都行），又能正常打开更新程序更新，就改成两个文件后不能打开更新程序，好迷茫，您代码是从哪里去启动的更新程序，我想看看毛病出在哪里
> > > 
> > > 
> > > 这个需要检查路径怎么配置的
> > > 因为遇到了占用问题，我就把占用的这句代码注释掉了
> > > ![image](https://user-images.githubusercontent.com/79817742/162404677-7023a2f6-214b-413f-999e-a112d7bbc588.png)
> > > 然后我调试找了一下 在下图中 当第二个压缩包到达时 解压过程中会报一个目标文件夹不存在的错误
> > > ![image](https://user-images.githubusercontent.com/79817742/162404552-60a11acc-11f4-4bfd-b7fe-8a3e4bbc0110.png)
> 
> 我不是很清楚你现在的状况，按照我的经验给你提几个建议你看看： 1.检查一下项目的引用是否正常，如果引用多了的话其它的DLL正在使用就会出现占用的情况 2.进程是否正常关闭线程是否正常推出 3.更新包（.zip）里的文件内容是否重复，版本号信息必须不一样。MD5码要对上

关于这个问题，我重新弄了一次，这次两个更新包中的内容不一样，但是还是不行，您想一想您代码里 是不是下载的时候要创建C:\\Users\\用户\\AppData\\Local\\Temp\\generalupdate_2022-04-09_patchs"这个文件夹，我调试发现当要解压第二个安装包时到达如图所示的地方，这个目录时不存在的，所以就抛出了目标地址不存在的错误
![image](https://user-images.githubusercontent.com/79817742/162550438-b275a2bd-08a8-448d-9949-4505bdd3e351.png)

**Comment by qq1176914912** [comment]
我看客户端设置的时候还有一个请求验证更新的服务端地址
![image](https://user-images.githubusercontent.com/79817742/162551290-7449f538-eec2-4c27-bf74-f9b9633a3d23.png)
对应服务端的这两个方法
![image](https://user-images.githubusercontent.com/79817742/162551301-35684e88-1791-48ed-938f-d10b5f29a4bd.png)
这个图中UpdateVersionDTO总的参数有什么说法 GetLastVersion（）中的版本有啥说法？

**Comment by JusterZhu** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/79817742/162375367-ca0ee53c-9a6c-4a51-aa0b-dedc804d5cfc.png) 我现在将服务器上的文件更改为了两个 主程序启动后下载完了两个 没有关闭主程序打开更新程序,我看了文件夹也只是吧第一个下载的压缩包解压了，第二个没有解压，但是只留一个文件（留那个都行），又能正常打开更新程序更新，就改成两个文件后不能打开更新程序，好迷茫，您代码是从哪里去启动的更新程序，我想看看毛病出在哪里
> > > > 
> > > > 
> > > > 这个需要检查路径怎么配置的
> > > > 因为遇到了占用问题，我就把占用的这句代码注释掉了
> > > > ![image](https://user-images.githubusercontent.com/79817742/162404677-7023a2f6-214b-413f-999e-a112d7bbc588.png)
> > > > 然后我调试找了一下 在下图中 当第二个压缩包到达时 解压过程中会报一个目标文件夹不存在的错误
> > > > ![image](https://user-images.githubusercontent.com/79817742/162404552-60a11acc-11f4-4bfd-b7fe-8a3e4bbc0110.png)
> > 
> > 
> > 我不是很清楚你现在的状况，按照我的经验给你提几个建议你看看： 1.检查一下项目的引用是否正常，如果引用多了的话其它的DLL正在使用就会出现占用的情况 2.进程是否正常关闭线程是否正常推出 3.更新包（.zip）里的文件内容是否重复，版本号信息必须不一样。MD5码要对上
> 
> 关于这个问题，我重新弄了一次，这次两个更新包中的内容不一样，但是还是不行，您想一想您代码里 是不是下载的时候要创建C:\Users\用户\AppData\Local\Temp\generalupdate_2022-04-09_patchs"这个文件夹，我调试发现当要解压第二个安装包时到达如图所示的地方，这个目录时不存在的，所以就抛出了目标地址不存在的错误 ![image](https://user-images.githubusercontent.com/79817742/162550438-b275a2bd-08a8-448d-9949-4505bdd3e351.png)

它会自动生成这个路径，找到是少配置路径了。你把引导类的启动配置发出来看看

**Comment by qq1176914912** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/79817742/162375367-ca0ee53c-9a6c-4a51-aa0b-dedc804d5cfc.png) 我现在将服务器上的文件更改为了两个 主程序启动后下载完了两个 没有关闭主程序打开更新程序,我看了文件夹也只是吧第一个下载的压缩包解压了，第二个没有解压，但是只留一个文件（留那个都行），又能正常打开更新程序更新，就改成两个文件后不能打开更新程序，好迷茫，您代码是从哪里去启动的更新程序，我想看看毛病出在哪里
> > > > > 
> > > > > 
> > > > > 这个需要检查路径怎么配置的
> > > > > 因为遇到了占用问题，我就把占用的这句代码注释掉了
> > > > > ![image](https://user-images.githubusercontent.com/79817742/162404677-7023a2f6-214b-413f-999e-a112d7bbc588.png)
> > > > > 然后我调试找了一下 在下图中 当第二个压缩包到达时 解压过程中会报一个目标文件夹不存在的错误
> > > > > ![image](https://user-images.githubusercontent.com/79817742/162404552-60a11acc-11f4-4bfd-b7fe-8a3e4bbc0110.png)
> > > 
> > > 
> > > 我不是很清楚你现在的状况，按照我的经验给你提几个建议你看看： 1.检查一下项目的引用是否正常，如果引用多了的话其它的DLL正在使用就会出现占用的情况 2.进程是否正常关闭线程是否正常推出 3.更新包（.zip）里的文件内容是否重复，版本号信息必须不一样。MD5码要对上
> > 
> > 
> > 关于这个问题，我重新弄了一次，这次两个更新包中的内容不一样，但是还是不行，您想一想您代码里 是不是下载的时候要创建C:\Users\用户\AppData\Local\Temp\generalupdate_2022-04-09_patchs"这个文件夹，我调试发现当要解压第二个安装包时到达如图所示的地方，这个目录时不存在的，所以就抛出了目标地址不存在的错误 ![image](https://user-images.githubusercontent.com/79817742/162550438-b275a2bd-08a8-448d-9949-4505bdd3e351.png)
> 
> 它会自动生成这个路径，找到是少配置路径了。你把引导类的启动配置发出来看看

不好意思，有点听不懂引导类的启动配置是哪个 0.0

**Comment by JusterZhu** [comment]
bootstrap的哪个类里面的config

**Comment by JusterZhu** [comment]
> 我看客户端设置的时候还有一个请求验证更新的服务端地址 ![image](https://user-images.githubusercontent.com/79817742/162551290-7449f538-eec2-4c27-bf74-f9b9633a3d23.png) 对应服务端的这两个方法 ![image](https://user-images.githubusercontent.com/79817742/162551301-35684e88-1791-48ed-938f-d10b5f29a4bd.png) 这个图中UpdateVersionDTO总的参数有什么说法 GetLastVersion（）中的版本有啥说法？

库里查出最新版本

**Comment by qq1176914912** [comment]
> bootstrap的哪个类里面的config

![image](https://user-images.githubusercontent.com/79817742/162553428-a0ac2dc2-cb6d-4a7f-8385-5299f698ca51.png)
这是我搜到的bootstrap的相关东西，你指的是哪个，我是用的您的这个github里面的源码的项目

**Comment by qq1176914912** [comment]
请问您现在这个是不是不支持文件夹的更新，我发现他是把文件夹的内容拿出来都放到一页上了

**Comment by JusterZhu** [comment]
> > bootstrap的哪个类里面的config
> 
> ![image](https://user-images.githubusercontent.com/79817742/162553428-a0ac2dc2-cb6d-4a7f-8385-5299f698ca51.png) 这是我搜到的bootstrap的相关东西，你指的是哪个，我是用的您的这个github里面的源码的项目

哎，有些基础的东西还是要自己看一眼。不能啥细节都问，Generaludpatebootstrap里你创建的时候不是配置了一个config方法吗。配置在那个里面

**Comment by qq1176914912** [comment]
> 

好吧，主要是我没创建，我直接用的是您的这个git上的项目，我想先试一试，可能是您在开发新功能的时候改了，我这也不了解，所以不能用吧

**Comment by qq1176914912** [comment]
> > > bootstrap的哪个类里面的config
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/79817742/162553428-a0ac2dc2-cb6d-4a7f-8385-5299f698ca51.png) 这是我搜到的bootstrap的相关东西，你指的是哪个，我是用的您的这个github里面的源码的项目
> 
> 哎，有些基础的东西还是要自己看一眼。不能啥细节都问，Generaludpatebootstrap里你创建的时候不是配置了一个config方法吗。配置在那个里面

好吧，主要是我没创建，我直接用的是您的这个git上的项目，我想先试一试，可能是您在开发新功能的时候改了，我这也不了解，所以不能用吧

**Comment by JusterZhu** [comment]
config这个方法一直存在于这个组件里

**Comment by JusterZhu** [comment]
我这几天准备出一套使用视频，完全能跑起来使用的教学。关注下b站的账号就行名字和我github的一样

**Comment by qq1176914912** [comment]
> > 请问您现在这个是不是不支持文件夹的更新，我发现他是把文件夹的内容拿出来都放到一页上了
> 
> 这个更新原理是把安装包的结构覆盖掉你主程序的结构，所以更新包的结构要和主程序的结构一致这样就能完全覆盖了。

那大致意思就是说 假如我想更新主程序的某个目录，这个目录首先一定要存在，如果不存在，他就会把更新目录下的这个文件夹里的文件都放到根目录，而不会自动创建这个目录

**Comment by JusterZhu** [comment]
> > > 请问您现在这个是不是不支持文件夹的更新，我发现他是把文件夹的内容拿出来都放到一页上了
> > 
> > 
> > 这个更新原理是把安装包的结构覆盖掉你主程序的结构，所以更新包的结构要和主程序的结构一致这样就能完全覆盖了。
> 
> 那大致意思就是说 假如我想更新主程序的某个目录，这个目录首先一定要存在，如果不存在，他就会把更新目录下的这个文件夹里的文件都放到根目录，而不会自动创建这个目录

嗯，程序是不知道你会新增目录的。如果不在更新包里把结构指定清楚它会把那些默认放到第一级目录下

**Comment by qq1176914912** [comment]
> 我这几天准备出一套使用视频，完全能跑起来使用的教学。关注下b站的账号就行名字和我github的一样

好的，麻烦大佬了，感谢大佬的耐心解释，问了这么多问题，万分感谢

**Comment by qq1176914912** [comment]
还有一个问题大佬，就是之前说的那个先后时序
![image](https://user-images.githubusercontent.com/79817742/162555770-94c4bd42-2175-45fc-a2f4-104ab3986a2a.png)
会影响后面解压更新时版本的顺序吗，例如1.1.1.1的版本的更新包，我写时间是2021年xxx，而1.1.1.2版本的更新包的时间我写2020年xxx,也就是新版本的时间比旧版本的时间还早，这么写会不会有影响，还是说1.1.1.2的更新包的时间必须要比1.1.1.1的更新包的时间晚，如果这样 我是不是可以把他理解为更新包的创建时间

**Comment by JusterZhu** [comment]
> 还有一个问题大佬，就是之前说的那个先后时序 ![image](https://user-images.githubusercontent.com/79817742/162555770-94c4bd42-2175-45fc-a2f4-104ab3986a2a.png) 会影响后面解压更新时版本的顺序吗，例如1.1.1.1的版本的更新包，我写时间是2021年xxx，而1.1.1.2版本的更新包的时间我写2020年xxx,也就是新版本的时间比旧版本的时间还早，这么写会不会有影响，还是说1.1.1.2的更新包的时间必须要比1.1.1.1的更新包的时间晚，如果这样 我是不是可以把他理解为更新包的创建时间

正常发布流程就不会有新版本时间比老版本早的，组件里会按照发布时间排序进行解压

**Comment by qq1176914912** [comment]
> > > > 请问您现在这个是不是不支持文件夹的更新，我发现他是把文件夹的内容拿出来都放到一页上了
> > > 
> > > 
> > > 这个更新原理是把安装包的结构覆盖掉你主程序的结构，所以更新包的结构要和主程序的结构一致这样就能完全覆盖了。
> > 
> > 
> > 那大致意思就是说 假如我想更新主程序的某个目录，这个目录首先一定要存在，如果不存在，他就会把更新目录下的这个文件夹里的文件都放到根目录，而不会自动创建这个目录
> 
> 嗯，程序是不知道你会新增目录的。如果不在更新包里把结构指定清楚它会把那些默认放到第一级目录下
我试了一下,我想要更新主程序所在目录某个文件夹里面的东西，往里面添加一些文件，压缩包zh中的路径为 up2/cer/文件
![image](https://user-images.githubusercontent.com/79817742/162559090-8e8516ad-0a39-4006-b60c-8a356a6d7ebf.png)
我主程序目录也是有这个文件夹的结构也相同
![image](https://user-images.githubusercontent.com/79817742/162559106-bc88c453-e693-4583-9b71-91a33b18f06e.png)
为什么更新完，他还是把东西放到了首页，难道说更新包中，不能存在单个文件夹吗

**Comment by qq1176914912** [comment]
我是了一下，我现在想在我主程序的某个目录下增加几个证书.cer文件 更新包路径是up2/cer
![image](https://user-images.githubusercontent.com/79817742/162560218-aed1026c-1e5d-4349-9e81-370bc3de8143.png)
主程序目录下有这个目录
![image](https://user-images.githubusercontent.com/79817742/162560241-c39519eb-f2e6-4364-aab8-5699d3094a36.png)
但是更新后依然放到了根目录，我调试发现，然后我怕是因为不能添加的原因，又增加了一个证书，想让更新包的证书替换他，但还是没有成功，依然放到了根目录

**Comment by qq1176914912** [comment]
我还是等您的过几天的最新视频和代码吧 感谢

**Comment by qq1176914912** [comment]
新问题：如果我在服务端进行了版本的验证，第一部检查更新助手的时候，假如我的更新助手不需要更新或者说服务器版本比实际版本低，我要怎么返回参数，才能让他正常进入第三部去打开更新助手程序，检查主程序是否需要更新，我这里写的，如果没有或者版本不对，返回一个空的 回去，但是并不能进入第三部，打开更新助手去检查主程序这个过程
![image](https://user-images.githubusercontent.com/79817742/162650464-13568ab7-4b57-469a-a201-ec077fcf7dea.png)

**Comment by JusterZhu** [comment]
这个需要重新走一遍下载流程然后会启动断点续传，理论上的逻辑更新功能只许前进不许退。回滚就达不到更新的目的了

**Comment by qq1176914912** [comment]
> 这个需要重新走一遍下载流程然后会启动断点续传，理论上的逻辑更新功能只许前进不许退。回滚就达不到更新的目的了

我在服务端进行了版本的验证，第一部检查更新助手的时候，假如我的更新助手不需要更新或者说服务器版本比实际版本低，我要怎么返回参数，才能让他正常进入第三部去打开更新助手程序，检查主程序是否需要更新，这里写的，如果没有或者版本不对，返回一个空的results回去，但是并不能进入第三部，打开更新助手去检查主程序这个过程，我也看了您的源码，貌似没有这样的一个处理
![image](https://user-images.githubusercontent.com/79817742/162658042-b2619efe-2d39-46f2-9298-695ec3904f41.png)

**Comment by JusterZhu** [comment]
你回传的result是null还是只是一个空集合，如果空集合不能启动的话我这晚上看看

**Comment by qq1176914912** [comment]
> 你回传的result是null还是只是一个空集合，如果空集合不能启动的话我这晚上看看

![image](https://user-images.githubusercontent.com/79817742/162660117-1de5b3f7-90ea-4696-9cc3-70e16611afb3.png)
不是null 是new完之后的一个空集合

**Comment by qq1176914912** [comment]
新问题：我的吧我主程序版本为1.1.1.3的debug目录下的文件压缩成了压缩包，当成1.1.1.3版本的更新包，然后上传到服务器，然后把本地版本改回1.1.1.2进行执行，当更新完成后，版本仍然但是1.1.1.2 只有当我将 本地的主程序exe名 改掉  启动更新 更新出来的新的exe才是最新版本，它并没有覆盖掉之前exe 
![image](https://user-images.githubusercontent.com/79817742/162697483-b1321a32-4509-4080-824e-639559983f57.png)

**Comment by JusterZhu** [comment]
> 新问题：我把我主程序版本为1.1.1.3的debug目录下的文件压缩成了压缩包，当成1.1.1.3版本的更新包，然后上传到服务器，然后把本地版本改回1.1.1.2进行执行，当更新完成后，版本仍然但是1.1.1.2 只有当我将 本地的主程序exe名 改掉 启动更新 更新出来的新的exe才是最新版本，它并没有覆盖掉之前exe 。注：更新助手并没有这个问题，可以成功覆盖更新 ![image](https://user-images.githubusercontent.com/79817742/162697483-b1321a32-4509-4080-824e-639559983f57.png)

更新助手能正常更新，主程序应该也可以。用的都是同一套代码，可能是主程序没关闭或者占用了。需要调试一下

**Comment by qq1176914912** [comment]
> > > 你回传的result是null还是只是一个空集合，如果空集合不能启动的话我这晚上看看
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/79817742/162660117-1de5b3f7-90ea-4696-9cc3-70e16611afb3.png) 不是null 是new完之后的一个空集合
> 
> 这是个bug，已经修复了。你明天拉代码

感谢大佬了，期待您新版本的nuget包
