### ISSUE TITLE
AbstractBootstrap.LaunchTaskAsync方法中的空指针异常

### ISSUE THREAD

**Issue by bruce-wei** [WELL-E/AutoUpdater#52]
在LaunchTaskAsync方法中，如果HttpUtil.GetTaskAsync<UpdateVersionsRespDTO>(url)的URL应各种原因无法访问，那么会返回null。此时下一句updateResp.Code便会报空指针异常。

**Comment by JusterZhu** [comment]
url不能访问是会抛出异常的，友好处理一下还是会以其它的方式手动抛出。

**Comment by bruce-wei** [comment]
我把返回default(T)改成了new T()，这样后面就不会报异常。而且这样的好处是，我们并不一定要一个获取更新地址的接口。

**Comment by JusterZhu** [comment]
有不错的修改可以提交PR
