### ISSUE TITLE
有项目打包和更新相关的文档吗？

### ISSUE THREAD

**Issue by li-zheng-hao** [WELL-E/AutoUpdater#54]
目前只看到了快速启动的文档，及b站的视频，有没有比较详尽一些的文档？关于打包和更新的流程

**Comment by JusterZhu** [comment]
详尽的文档正在设计，会更新到http://justerzhu.cn/ 官网上。您有想看到文档内容的建议可以提出来，我正好收集意见。

**Comment by li-zheng-hao** [comment]
非常感谢，周末有空看一下您发布的视频先，如果有什么疑问或建议我会提出来的
