### ISSUE TITLE
是否支持更新可选项及更新内容？

### ISSUE THREAD

**Issue by li-zheng-hao** [WELL-E/AutoUpdater#55]
1. 在upgrade端是否支持判断client需要更新并给用户选择是否更新的功能？
> 在[微信文档](https://mp.weixin.qq.com/s/pRKPFe3eC0NSqv9ixXEiTg)中并未找到相关说明，但是在readme中看到`非强制更新可以弹出选择框供用户选择，强制更新则直接更新`，是否有示例demo或相关文档说明？
4. 在upgrade端是否支持获取不同版本的更新内容，方便展示给用户？(在server端的表中没看到更新信息的字段)

**Comment by JusterZhu** [comment]
视频教程里有说明如何使用。

**Comment by JusterZhu** [comment]
使用GeneralClientBootstrap对象初始化SetCustomOption即可。
