### ISSUE TITLE
打包工具启动无反应

### ISSUE THREAD

**Issue by li-zheng-hao** [WELL-E/AutoUpdater#56]
环境：win10 家庭版 21H1

问题：安装完成后启动无反应，安装目录下也没有日志文件，不知道什么原因？

**Comment by li-zheng-hao** [comment]
![image](https://user-images.githubusercontent.com/22129824/176858201-9fd0f467-0909-4f3a-b516-4ab49d26787a.png)
看了一下我的vs，本地应该是有.net5的运行环境的

**Comment by JusterZhu** [comment]
这个在部分开发者的电脑上确实有这类问题，可以下载源码编译一个版本使用。
