### ISSUE TITLE
源码编译以及类名问题

### ISSUE THREAD

**Issue by NullRefer** [WELL-E/AutoUpdater#6]
您好，我在下载源码后，进行编译，发现源代码存在一个问题，在 `Core` 项目中，`StringEx.cs` 这个文件重复出现了两次，一个路径为 `./StringEx.cs`，另一个在 `./Utils/StringEx.cs`

然后就是默认的 `Strategy` 命名应该是漏了一个 `a`，`DefultStrategy` -> `DefaultStrategy`
`AbstractBootstrap` 类中，在 `Private Members` 里面, `DefultFormat` -> `DefaultFormat`

最后, 非常感谢作者的开源奉献!

**Comment by JusterZhu** [comment]
谢谢指出，下一个版本中会及时修正
