### ISSUE TITLE
下载中途断网，到达超时时间没有异常上抛

### ISSUE THREAD

**Issue by lhyAira** [WELL-E/AutoUpdater#7]
![image](https://user-images.githubusercontent.com/36753167/150753304-9cc3f5b2-43b5-4a7d-8e67-e22a20f87f17.png)
下载过程中，中断网络，到达超时时间没有异常上抛，网络恢复后会catch该异常信息，麻烦大佬看看肿么解决呢

**Comment by JusterZhu** [comment]
- [ ] BUG Download task

**Comment by JusterZhu** [comment]
- [ ]
