### ISSUE TITLE
配置适应MAUI - Windows machice

### ISSUE THREAD

**Issue by JusterZhu** [WELL-E/AutoUpdater#8]
需在AutoUpdate.MauiApp-Sample中开发
1.让GeneralUpdate整套组件适应MAUI的框架，并能在window client的环境下正常更新

**Comment by JaneConan** [comment]
https://github.com/WELL-E/AutoUpdater/pull/34

提了一个pr简单尝试

![image](https://user-images.githubusercontent.com/26090153/158054971-1c8bea5e-d5a2-499f-a5e3-02d27534860d.png)

**Comment by JusterZhu** [comment]
At present, the Windows machine process startup encounters a bug .
https://github.com/dotnet/maui/issues/5327
